language: node_js
branches:
  only:
  - pages-origin
cache: 
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_2548ca7ff03a_key -iv $encrypted_2548ca7ff03a_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "esappear"
- git config --global user.email 624835942@qq.com
- npm install -g hexo
- npm install -g hexo-cli
- git clone https://github.com/iissnan/hexo-theme-next themes/next
install:
- npm install
script:
- hexo clean
- hexo g
after_success:
- hexo d
