language: node_js
node_js:
  - "7" 
branches:
  only:
  - pages-origin
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_2548ca7ff03a_key -iv $encrypted_2548ca7ff03a_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "esappear"
- git config --global user.email 624835942@qq.com
#- git clone https://github.com/iissnan/hexo-theme-next themes/next
install:
- npm install
script:
- ./node_modules/hexo/bin/hexo clean
- ./node_modules/hexo/bin/hexo g
after_success:
- ./node_modules/hexo/bin/hexo d
