language: node_js
branches:
  only:
  -  pages-origin
before_install:
- npm install -g hexo
- npm install -g hexo-cli
- git clone https://github.com/iissnan/hexo-theme-next themes/next
install:
- npm install
script:
- hexo clean
- hexo g
after_success:
- hexo d
